---
- name: Update apt
  apt: update_cache=yes
- name: Install rsyslog2
  shell: "{{ item }}"
  with_items:
    - 'rm -rf /tmp-rsyslog'
    - 'mkdir /tmp-rsyslog'
    - 'cd /tmp-rsyslog'
    - 'wget https://github.com/papertrail/remote_syslog2/releases/download/v0.19/remote_syslog_linux_amd64.tar.gz'
    - 'tar xzf ./remote_syslog*.tar.gz'
    - 'sudo cp ./remote_syslog/remote_syslog /usr/local/bin'
    - 'rm -rf /tmp-rsyslog'
