---
- stat:
    path: "/var/www/{{ application }}"
  register: appDirectory

- name: Stop Puma server
  shell: kill -9 $(cat puma.pid)
  args:
    chdir: "/var/www/{{ application }}"
  when: appDirectory.isdir is defined

- name: Delete directory
  remote_user: deployer
  file:
    path: "/var/www/{{ application }}"
    state: absent

- name: Create directory
  remote_user: deployer
  file:
    path: "/var/www/{{ application }}"
    state: directory

- name: Add Git remote
  remote_user: deployer
  shell: "git clone https://github.com/{{ applicationFull }}.git ."
  args:
    chdir: "/var/www/{{ application }}"
