---
- name: Create directory
  remote_user: deployer
  file:
    path: /var/www/sinatra
    state: directory

- name: Copy files (1)
  remote_user: deployer
  template:
    src: Gemfile
    dest: /var/www/sinatra/Gemfile

- name: Copy files (2)
  remote_user: deployer
  template:
    src: app.rb
    dest: /var/www/sinatra/app.rb

- name: Copy files (3)
  remote_user: deployer
  template:
    src: config.ru
    dest: /var/www/sinatra/config.ru

- name: Install packages
  remote_user: deployer
  command: "bundle install"
  args:
    chdir: /var/www/sinatra

- name: Stop Puma server
  shell: kill -9 $(cat puma.pid)
  args:
    chdir: /var/www/sinatra

- name: Boot server
  command: "bundle exec puma --daemon --bind unix://puma.sock --pidfile puma.pid"
  args:
    chdir: /var/www/sinatra

- name: Change socket permissions
  file:
    path: /var/www/sinatra/puma.sock
    state: file
    mode: 0666
