---
- name: Installing NGINX
  remote_user: deployer
  apt:
    pkg: nginx
    state: latest

- name: Remove default NGINX config
  remote_user: deployer
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload NGINX

- name: Deploy NGINX config
  remote_user: deployer
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/web.conf
  notify: Reload NGINX

- name: Deploy NGINX template
  remote_user: deployer
  template:
    src: index.html
    dest: /var/www/html/index.html

- name: Starting NGINX
  remote_user: deployer
  service:
    name: nginx
    state: started
