---
- name: Instal NGINX
  remote_user: deployer
  apt:
    pkg: nginx
    state: latest

- name: Remove default NGINX config
  remote_user: deployer
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload NGINX

- name: Push NGINX config
  remote_user: deployer
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/web.conf
  notify: Reload NGINX

- name: Start NGINX
  remote_user: deployer
  service:
    name: nginx
    state: started
